/* write a programe to input any string and impliment strlen() and
strcmp() in a single string */
#include<stdio.h>
#include<conio.h>
void main()
{
     char a1[10],a2[10],i,j;
     clrscr();
     printf("\n enter first string:");
     gets(a1);
     i=strlen(a1);
     printf("%d",i);
     printf("\n enter second string:");
     gets(a2);
if(strcmp(s1,s2)==0)
	{
		printf("\n you entered the same string two times:");
	}
	else
	{
		printf("\n you entered string are not same:");
	}
	getch();
}

